package main

// ============================================================
// Lab 02 — Chord DHT
// File: main.go
// Role: Entry point — server mode and CLI mode
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN (inside your container):
//
//   Start this node (server mode):
//     ./chord_bin -mode server -port 7000 -host 10.8.100.22
//
//   Join an existing ring:
//     ./chord_bin -mode server -port 7000 -host 10.8.100.1 -join 10.8.100.22:7000
//
//   Use the CLI (from another terminal in the same container):
//     ./chord_bin -mode cli -port 7000 put hello world
//     ./chord_bin -mode cli -port 7000 get hello
//     ./chord_bin -mode cli -port 7000 delete hello
//     ./chord_bin -mode cli -port 7000 info
//     ./chord_bin -mode cli -port 7000 ring
//     ./chord_bin -mode cli -port 7000 storage
//
//   Recompile after editing:
//     pkill chord_bin
//     go build -o chord_bin .
//     ./chord_bin -mode server -port 7000 -host 10.8.100.22 &
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"time"
)

func main() {
	mode := flag.String("mode", "server", "Run mode: 'server' or 'cli'")
	port := flag.String("port", "7000", "Port this node listens on")
	host := flag.String("host", "10.8.100.22", "This machine's IP address")
	join := flag.String("join", "", "Address of existing node to join (e.g. 10.8.100.22:7000)")
	flag.Parse()

	switch *mode {
	case "server":
		runServer(*port, *host, *join)
	case "cli":
		runCLI(*port, flag.Args())
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode %q — use 'server' or 'cli'\n", *mode)
		os.Exit(1)
	}
}

// ── Server mode ──────────────────────────────────────────────

func runServer(port, host, joinAddr string) {
	addr := fmt.Sprintf("%s:%s", host, port)

	fmt.Println("============================================")
	fmt.Printf(" Lab 02 — Chord DHT Node\n")
	fmt.Printf(" Address : %s\n", addr)
	if joinAddr != "" {
		fmt.Printf(" Joining : %s\n", joinAddr)
	} else {
		fmt.Printf(" Mode    : Creating new ring\n")
	}
	fmt.Println("============================================")

	// Create node
	n := newNode(addr)
	log.Printf("[CHORD] Node ID = %d", n.info.ID)

	// Start RPC server
	if err := startRPCServer(n, port); err != nil {
		log.Fatalf("[CHORD] Failed to start RPC server: %v", err)
	}

	// Join or create ring
	if err := n.join(joinAddr); err != nil {
		log.Fatalf("[CHORD] Failed to join ring: %v", err)
	}

	if joinAddr == "" {
		log.Printf("[CHORD] New ring created — this node is alone")
	} else {
		log.Printf("[CHORD] Joined ring via %s  successor=ID:%d",
			joinAddr, n.successor().ID)
	}

	// Start background maintenance
	n.startBackgroundTasks()

	// Give ring time to stabilize before accepting CLI commands
	time.Sleep(1 * time.Second)
	log.Printf("[CHORD] Node ready. Use: ./chord_bin -mode cli -port %s <command>", port)

	// Block forever
	select {}
}

// ── CLI mode ─────────────────────────────────────────────────

func runCLI(port string, args []string) {
	nodeAddr := fmt.Sprintf("127.0.0.1:%s", port)

	if len(args) == 0 {
		printCLIUsage()
		return
	}

	cmd := args[0]

	switch cmd {
	case "put":
		if len(args) < 3 {
			fmt.Println("Usage: chord_bin -mode cli -port <port> put <key> <value>")
			return
		}
		var reply PutReply
		err := callRPC(nodeAddr, "ChordRPC.Put",
			&PutArgs{Key: args[1], Value: args[2]}, &reply)
		if err != nil {
			log.Fatalf("put failed: %v", err)
		}
		fmt.Printf("✅ Stored  key=%q  value=%q\n", args[1], args[2])

	case "get":
		if len(args) < 2 {
			fmt.Println("Usage: chord_bin -mode cli -port <port> get <key>")
			return
		}
		var reply GetReply
		err := callRPC(nodeAddr, "ChordRPC.Get", &GetArgs{Key: args[1]}, &reply)
		if err != nil {
			log.Fatalf("get failed: %v", err)
		}
		if reply.Found {
			fmt.Printf("✅ key=%q  value=%q\n", args[1], reply.Value)
		} else {
			fmt.Printf("❌ key=%q not found\n", args[1])
		}

	case "delete":
		if len(args) < 2 {
			fmt.Println("Usage: chord_bin -mode cli -port <port> delete <key>")
			return
		}
		var reply DeleteReply
		err := callRPC(nodeAddr, "ChordRPC.Delete", &DeleteArgs{Key: args[1]}, &reply)
		if err != nil {
			log.Fatalf("delete failed: %v", err)
		}
		if reply.Deleted {
			fmt.Printf("✅ Deleted key=%q\n", args[1])
		} else {
			fmt.Printf("❌ key=%q not found\n", args[1])
		}

	case "info":
		var reply FindSuccessorReply
		err := callRPC(nodeAddr, "ChordRPC.FindSuccessor",
			&FindSuccessorArgs{ID: 0}, &reply)
		if err != nil {
			log.Fatalf("info failed: %v", err)
		}
		fmt.Println("[INFO] Node is reachable — use 'ring' and 'storage' for details")

	case "ring":
		fmt.Println("Use 'info' command in the server terminal for ring details")
		fmt.Println("Or check the server logs with: bash docker/scripts/logs.sh <group>")

	case "storage":
		fmt.Println("Storage details are shown in the server terminal")
		fmt.Println("Or check the server logs with: bash docker/scripts/logs.sh <group>")

	case "ping":
		err := callRPC(nodeAddr, "ChordRPC.Ping", &PingArgs{}, &PingReply{})
		if err != nil {
			fmt.Printf("❌ Node not responding: %v\n", err)
		} else {
			fmt.Println("✅ Node is alive")
		}

	default:
		fmt.Printf("Unknown command: %q\n", cmd)
		printCLIUsage()
	}
}

func printCLIUsage() {
	fmt.Println(`
Chord DHT CLI — Usage:
  ./chord_bin -mode cli -port <port> <command>

Commands:
  put <key> <value>   Store a key-value pair in the DHT
  get <key>           Retrieve a value from the DHT
  delete <key>        Delete a key from the DHT
  ping                Check if this node is running
  info                Show node info
`)
}
