package main

// ============================================================
// Lab 07 — Consensus (Simplified Raft)
// File: main.go
// Role: Entry point — node and client modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN:
//   Start a Raft node:
//     ./raft_bin -mode node -id raft-node1 -port 9400 \
//       -peers raft-node2:9401,raft-node3:9402,raft-node4:9403,raft-node5:9404
//
//   Submit a command (SET):
//     ./raft_bin -mode client -node raft-node1:9400 -cmd "SET city London"
//
//   Read a value (GET):
//     ./raft_bin -mode client -node raft-node1:9400 -get city
//
//   Check node status:
//     ./raft_bin -mode client -node raft-node1:9400 -status
//
//   Watch cluster (check all 5 nodes):
//     ./raft_bin -mode watch
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

const (
	NODE1 = "raft-node1:9400"
	NODE2 = "raft-node2:9401"
	NODE3 = "raft-node3:9402"
	NODE4 = "raft-node4:9403"
	NODE5 = "raft-node5:9404"
)

var allNodes = []string{NODE1, NODE2, NODE3, NODE4, NODE5}

func main() {
	mode  := flag.String("mode", "node", "Mode: node | client | watch")
	id    := flag.String("id", "raft-node1", "Node ID (node mode)")
	port  := flag.String("port", "9400", "Port to listen on (node mode)")
	peers := flag.String("peers", "", "Comma-separated peer addresses (node mode)")
	node  := flag.String("node", NODE1, "Node address to talk to (client mode)")
	cmd   := flag.String("cmd", "", "Command to submit e.g. 'SET city London'")
	get   := flag.String("get", "", "Key to read from state machine")
	status:= flag.Bool("status", false, "Show node status")
	flag.Parse()

	switch *mode {
	case "node":
		runNode(*id, *port, *peers)
	case "client":
		runClient(*node, *cmd, *get, *status)
	case "watch":
		runWatch()
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode: %s\n", *mode)
		os.Exit(1)
	}
}

func runNode(id, port, peersStr string) {
	var peers []string
	if peersStr != "" {
		peers = strings.Split(peersStr, ",")
	}

	addr := fmt.Sprintf("%s:%s", id, port)

	fmt.Println("============================================")
	fmt.Printf(" Lab 07 — Raft Node\n")
	fmt.Printf(" ID:    %s\n", id)
	fmt.Printf(" Addr:  %s\n", addr)
	fmt.Printf(" Peers: %d\n", len(peers))
	fmt.Println("============================================")

	n := NewNode(id, addr, peers)
	if n == nil {
		log.Fatal("[RAFT] NewNode returned nil — complete Task 1")
	}

	if err := startRPCServer(n, port); err != nil {
		log.Fatalf("[RAFT] Failed to start RPC server: %v", err)
	}

	fmt.Printf("[RAFT] Node %s ready\n", id)
	select {}
}

func runClient(nodeAddr, cmd, getKey string, showStatus bool) {
	if showStatus {
		var reply StatusReply
		if err := callRPC(nodeAddr, "RaftRPC.Status", &StatusArgs{}, &reply); err != nil {
			log.Fatalf("Status failed: %v", err)
		}
		fmt.Printf("\n── Node Status: %s ──────────────────────────\n", nodeAddr)
		fmt.Printf("  State:     %s\n", reply.State)
		fmt.Printf("  Term:      %d\n", reply.Term)
		fmt.Printf("  Log:       %d entries\n", reply.LogLen)
		fmt.Printf("  Committed: %d\n", reply.Committed)
		fmt.Printf("  Leader:    %s\n", reply.Leader)
		fmt.Println()
		return
	}

	if getKey != "" {
		var reply GetValueReply
		if err := callRPC(nodeAddr, "RaftRPC.GetValue", &GetValueArgs{Key: getKey}, &reply); err != nil {
			log.Fatalf("GetValue failed: %v", err)
		}
		if reply.Found {
			fmt.Printf("✅ key=%q value=%q\n", getKey, reply.Value)
		} else {
			fmt.Printf("❌ key=%q not found\n", getKey)
		}
		return
	}

	if cmd != "" {
		var reply SubmitReply
		if err := callRPC(nodeAddr, "RaftRPC.Submit", &SubmitArgs{Command: cmd}, &reply); err != nil {
			log.Fatalf("Submit failed: %v", err)
		}
		if reply.Success {
			fmt.Printf("✅ Command committed: %q\n", cmd)
		} else {
			fmt.Printf("❌ Failed: %s (leader: %s)\n", reply.Err, reply.Leader)
		}
		return
	}

	fmt.Println("Usage: -cmd 'SET key val' | -get key | -status")
}

func runWatch() {
	fmt.Println("Watching cluster (Ctrl+C to stop)...")
	for {
		fmt.Printf("\n── Cluster Status @ %s ─────────────────────\n",
			time.Now().Format("15:04:05"))
		for _, addr := range allNodes {
			var reply StatusReply
			err := callRPC(addr, "RaftRPC.Status", &StatusArgs{}, &reply)
			if err != nil {
				fmt.Printf("  %-20s  ❌ unreachable\n", addr)
				continue
			}
			leader := ""
			if reply.State == Leader {
				leader = " ← LEADER"
			}
			fmt.Printf("  %-20s  %-10s  term=%-3d  log=%-3d  committed=%-3d%s\n",
				addr, reply.State, reply.Term, reply.LogLen, reply.Committed, leader)
		}
		time.Sleep(1 * time.Second)
	}
}
