package lab04complete

// ============================================================
// Lab 04 — RPC and Web Services
// File: main.go  (client)
// Role: CLI + benchmark runner
//
// DO NOT EDIT THIS FILE
//
// HOW TO USE:
//   # Individual commands
//   ./client_bin rpc put city London
//   ./client_bin grpc get city
//   ./client_bin rest delete city
//   ./client_bin rest list
//
//   # Benchmark — compare all three
//   ./client_bin bench 100
//
//   # All protocols at once
//   ./client_bin all put city London
//   ./client_bin all get city
// ============================================================

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	SERVER_HOST = "lab04-server"
	RPC_ADDR    = SERVER_HOST + ":7000"
	GRPC_ADDR   = SERVER_HOST + ":7001"
	REST_URL    = "http://" + SERVER_HOST + ":8080"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		return
	}

	protocol := os.Args[1]
	if protocol == "bench" {
		n := 100
		if len(os.Args) >= 3 {
			n, _ = strconv.Atoi(os.Args[2])
		}
		runBenchmark(n)
		return
	}

	if len(os.Args) < 4 && protocol != "all" {
		printUsage()
		return
	}

	cmd := os.Args[2]
	key := ""
	value := ""
	if len(os.Args) >= 4 { key = os.Args[3] }
	if len(os.Args) >= 5 { value = os.Args[4] }

	switch protocol {
	case "rpc":
		runRPC(cmd, key, value)
	case "grpc":
		runGRPC(cmd, key, value)
	case "rest":
		runREST(cmd, key, value)
	case "all":
		if len(os.Args) >= 4 { cmd = os.Args[2]; key = os.Args[3] }
		if len(os.Args) >= 5 { value = os.Args[4] }
		fmt.Println("── net/rpc ──────────────────")
		runRPC(cmd, key, value)
		fmt.Println("── gRPC ─────────────────────")
		runGRPC(cmd, key, value)
		fmt.Println("── REST ─────────────────────")
		runREST(cmd, key, value)
	default:
		printUsage()
	}
}

func runRPC(cmd, key, value string) {
	c := NewRPCClient(RPC_ADDR)
	if err := c.Connect(); err != nil {
		fmt.Printf("❌ net/rpc connect failed: %v\n", err)
		return
	}
	defer c.Close()
	execCmd("net/rpc", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func runGRPC(cmd, key, value string) {
	c := NewGRPCClient(GRPC_ADDR)
	if err := c.Connect(); err != nil {
		fmt.Printf("❌ gRPC connect failed: %v\n", err)
		return
	}
	defer c.Close()
	execCmd("gRPC", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func runREST(cmd, key, value string) {
	c := NewRESTClient(REST_URL)
	execCmd("REST", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func execCmd(proto, cmd, key, value string,
	putFn func() error,
	getFn func() (string, bool, error),
	delFn func() (bool, error),
	listFn func() ([]string, error)) {

	switch cmd {
	case "put":
		if err := putFn(); err != nil {
			fmt.Printf("❌ [%s] put failed: %v\n", proto, err)
		} else {
			fmt.Printf("✅ [%s] Stored key=%q value=%q\n", proto, key, value)
		}
	case "get":
		val, found, err := getFn()
		if err != nil {
			fmt.Printf("❌ [%s] get failed: %v\n", proto, err)
		} else if found {
			fmt.Printf("✅ [%s] key=%q value=%q\n", proto, key, val)
		} else {
			fmt.Printf("❌ [%s] key=%q not found\n", proto, key)
		}
	case "delete":
		deleted, err := delFn()
		if err != nil {
			fmt.Printf("❌ [%s] delete failed: %v\n", proto, err)
		} else if deleted {
			fmt.Printf("✅ [%s] Deleted key=%q\n", proto, key)
		} else {
			fmt.Printf("❌ [%s] key=%q not found\n", proto, key)
		}
	case "list":
		keys, err := listFn()
		if err != nil {
			fmt.Printf("❌ [%s] list failed: %v\n", proto, err)
		} else {
			fmt.Printf("✅ [%s] %d keys: %v\n", proto, len(keys), keys)
		}
	default


// ============================================================
// Lab 04 — RPC and Web Services
// File: types.go  (net/rpc)
// Role: Request and reply types for the net/rpc server
//
// TASK IN THIS FILE:
//   Task 1 — Define all request and reply structs
// ============================================================

// ============================================================
// TASK 1 — Define net/rpc Request and Reply Types
// ============================================================
// net/rpc requires every method argument and return value to
// be a struct. Define the following 8 structs:
//
// PutArgs   { Key string, Value string }
// PutReply  { Success bool }
//
// GetArgs   { Key string }
// GetReply  { Value string, Found bool }
//
// DeleteArgs  { Key string }
// DeleteReply { Deleted bool }
//
// ListArgs  {}  (empty — no arguments needed)
// ListReply { Keys []string }
//
// IMPORTANT: All field names must start with a CAPITAL letter.
// net/rpc uses encoding/gob for serialisation — unexported
// (lowercase) fields are silently ignored and cause subtle bugs.
//
// TODO: define all 8 structs below

type PutArgs struct {
	Key   string
	Value string
}
type PutReply struct {
	Success bool
}

type GetArgs struct {
	Key string
}
type GetReply struct {
	Value string
	Found bool
}

type DeleteArgs struct {
	Key string
}
type DeleteReply struct {
	Deleted bool
}

type ListArgs struct{}
type ListReply struct {
	Keys []string
}