package main

// ============================================================
// Lab 06 — Caching and Replication
// File: main.go
// Role: Entry point — origin, cache, client modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN:
//   Origin server:
//     ./cache_bin -mode origin -port 9300
//
//   Cache node (primary or replica):
//     ./cache_bin -mode cache -port 9200 -origin origin:9300 -capacity 10
//
//   Register a replica with the primary:
//     ./cache_bin -mode register -primary cache-primary:9200 -replica cache-replica1:9200
//
//   Client — get a key:
//     ./cache_bin -mode get -cache cache-primary:9200 -key mykey
//
//   Client — set a key (write-through):
//     ./cache_bin -mode set -cache cache-primary:9200 -key mykey -value hello -strategy write-through
//
//   Client — set a key (write-back):
//     ./cache_bin -mode set -cache cache-primary:9200 -key mykey -value hello -strategy write-back
//
//   Show stats:
//     ./cache_bin -mode stats -cache cache-primary:9200
//
//   Run benchmark (measure hit rate warmup):
//     ./cache_bin -mode bench -cache cache-primary:9200
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"time"
)

func main() {
	mode     := flag.String("mode", "cache", "Mode: origin | cache | get | set | stats | bench | register")
	port     := flag.String("port", "9200", "Port for origin or cache server")
	origin   := flag.String("origin", "origin:9300", "Origin server address")
	cacheAddr:= flag.String("cache", "cache-primary:9200", "Cache server address")
	primary  := flag.String("primary", "cache-primary:9200", "Primary cache address (register mode)")
	replica  := flag.String("replica", "", "Replica address to register (register mode)")
	key      := flag.String("key", "", "Key for get/set operations")
	value    := flag.String("value", "", "Value for set operation")
	strategy := flag.String("strategy", "write-through", "Write strategy: write-through | write-back")
	capacity := flag.Int("capacity", 10, "Cache capacity (max number of keys)")
	flag.Parse()

	switch *mode {
	case "origin":
		fmt.Println("============================================")
		fmt.Println(" Lab 06 — Origin Database")
		fmt.Println("============================================")
		StartOriginServer(*port, 50*time.Millisecond)

	case "cache":
		fmt.Println("============================================")
		fmt.Printf(" Lab 06 — Cache Node (capacity=%d)\n", *capacity)
		fmt.Printf(" Origin: %s\n", *origin)
		fmt.Println("============================================")

		cache := NewCache(*capacity)
		if cache == nil {
			log.Fatal("[CACHE] NewCache returned nil — complete Task 1")
		}

		originClient := NewOriginClient(*origin)
		replication  := NewReplicationManager()

		if err := startRPCServer(cache, originClient, replication, *port); err != nil {
			log.Fatalf("[CACHE] Failed to start: %v", err)
		}

		startFlushWorker(cache, originClient, 3*time.Second)

		fmt.Printf("[CACHE] Ready on port %s\n", *port)
		select {}

	case "register":
		if *replica == "" {
			fmt.Fprintln(os.Stderr, "Usage: -mode register -primary <addr> -replica <addr>")
			os.Exit(1)
		}
		var reply RegisterReplicaReply
		err := callRPC(*primary, "CacheRPC.RegisterReplica",
			&RegisterReplicaArgs{Addr: *replica}, &reply)
		if err != nil {
			log.Fatalf("RegisterReplica failed: %v", err)
		}
		fmt.Printf("✅ Registered replica %s with primary %s\n", *replica, *primary)

	case "get":
		if *key == "" { fmt.Fprintln(os.Stderr, "Usage: -mode get -cache <addr> -key <key>"); os.Exit(1) }
		start := time.Now()
		var reply GetReply
		err := callRPC(*cacheAddr, "CacheRPC.Get", &GetArgs{Key: *key}, &reply)
		elapsed := time.Since(start)
		if err != nil {
			log.Fatalf("Get failed: %v", err)
		}
		if reply.Found {
			source := "cache"
			if reply.FromOrigin { source = "origin (cache miss)" }
			fmt.Printf("✅ key=%-20q value=%-20q [%s] latency=%v\n",
				*key, reply.Value, source, elapsed)
		} else {
			fmt.Printf("❌ key=%q not found\n", *key)
		}

	case "set":
		if *key == "" || *value == "" {
			fmt.Fprintln(os.Stderr, "Usage: -mode set -cache <addr> -key <key> -value <value> -strategy <strategy>")
			os.Exit(1)
		}
		start := time.Now()
		var reply SetReply
		err := callRPC(*cacheAddr, "CacheRPC.Set",
			&SetArgs{Key: *key, Value: *value, Strategy: *strategy}, &reply)
		elapsed := time.Since(start)
		if err != nil {
			log.Fatalf("Set failed: %v", err)
		}
		fmt.Printf("✅ Set key=%-20q value=%-20q strategy=%s latency=%v\n",
			*key, *value, *strategy, elapsed)

	case "stats":
		var reply StatsReply
		err := callRPC(*cacheAddr, "CacheRPC.GetStats", &StatsArgs{}, &reply)
		if err != nil {
			log.Fatalf("GetStats failed: %v", err)
		}
		fmt.Printf("\n── Cache Statistics (%s) ──────────────────\n", *cacheAddr)
		fmt.Printf("  Hits:      %d\n", reply.Hits)
		fmt.Printf("  Misses:    %d\n", reply.Misses)
		fmt.Printf("  Evictions: %d\n", reply.Evictions)
		fmt.Printf("  Hit Rate:  %.1f%%\n\n", reply.HitRate*100)

	case "bench":
		runBenchmark(*cacheAddr)

	default:
		fmt.Fprintf(os.Stderr, "Unknown mode: %s\n", *mode)
		os.Exit(1)
	}
}

func runBenchmark(cacheAddr string) {
	fmt.Println("\n════════════════════════════════════════════")
	fmt.Println(" Lab 06 — Benchmark: Hit Rate Warmup")
	fmt.Println("════════════════════════════════════════════")

	keys := []string{"alpha", "beta", "gamma", "delta", "epsilon"}

	// Round 1 — all misses (cold cache)
	fmt.Println("\n── Round 1: Cold Cache (all misses expected) ──")
	for _, k := range keys {
		start := time.Now()
		var reply GetReply
		callRPC(cacheAddr, "CacheRPC.Get", &GetArgs{Key: k}, &reply)
		elapsed := time.Since(start)
		source := "MISS (origin)"
		if !reply.FromOrigin && reply.Found { source = "HIT (cache)" }
		fmt.Printf("  key=%-10q %s  latency=%v\n", k, source, elapsed)
	}

	// Round 2 — all hits (warm cache)
	fmt.Println("\n── Round 2: Warm Cache (all hits expected) ──")
	for _, k := range keys {
		start := time.Now()
		var reply GetReply
		callRPC(cacheAddr, "CacheRPC.Get", &GetArgs{Key: k}, &reply)
		elapsed := time.Since(start)
		source := "MISS (origin)"
		if !reply.FromOrigin && reply.Found { source = "HIT (cache)" }
		fmt.Printf("  key=%-10q %s  latency=%v\n", k, source, elapsed)
	}

	// Stats
	var stats StatsReply
	callRPC(cacheAddr, "CacheRPC.GetStats", &StatsArgs{}, &stats)
	fmt.Printf("\n── Final Stats ──────────────────────────────\n")
	fmt.Printf("  Hits: %d  Misses: %d  Hit Rate: %.1f%%\n\n",
		stats.Hits, stats.Misses, stats.HitRate*100)
}
