package main

// ============================================================
// Lab 06 — Caching and Replication
// File: origin.go
// Role: Simulated slow origin (database)
//
// DO NOT EDIT THIS FILE
//
// This simulates a slow database by adding a 50ms delay to
// every read. This makes the performance difference between
// a cache hit (fast) and a cache miss (goes to origin = slow)
// clearly visible in experiments.
// ============================================================

import (
	"fmt"
	"net"
	"net/rpc"
	"sync"
	"time"
)

// OriginDB is the server-side origin (runs in the origin container)
type OriginDB struct {
	mu    sync.RWMutex
	store map[string]string
	delay time.Duration
}

type OriginGetArgs struct{ Key string }
type OriginGetReply struct {
	Value string
	Found bool
}
type OriginSetArgs struct{ Key, Value string }
type OriginSetReply struct{ Success bool }

func (o *OriginDB) Get(args *OriginGetArgs, reply *OriginGetReply) error {
	time.Sleep(o.delay) // simulate slow DB read
	o.mu.RLock()
	defer o.mu.RUnlock()
	val, ok := o.store[args.Key]
	reply.Value = val
	reply.Found = ok
	if ok {
		fmt.Printf("[ORIGIN] Get key=%-20q → found (simulated %v delay)\n", args.Key, o.delay)
	} else {
		fmt.Printf("[ORIGIN] Get key=%-20q → not found\n", args.Key)
	}
	return nil
}

func (o *OriginDB) Set(args *OriginSetArgs, reply *OriginSetReply) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.store[args.Key] = args.Value
	time.Sleep(o.delay) // simulate slow DB write
	reply.Success = true
	fmt.Printf("[ORIGIN] Set key=%-20q value=%q\n", args.Key, args.Value)
	return nil
}

func StartOriginServer(port string, delay time.Duration) {
	db := &OriginDB{
		store: make(map[string]string),
		delay: delay,
	}

	// Pre-populate with some data
	for i := 0; i < 20; i++ {
		db.store[fmt.Sprintf("preloaded-key-%d", i)] = fmt.Sprintf("preloaded-value-%d", i)
	}

	db.store["alpha"] = "test_val"
	db.store["beta"] = "test_val"
	db.store["gamma"] = "test_val"
	db.store["delta"] = "test_val"
	db.store["epsilon"] = "test_val"

	server := rpc.NewServer()
	server.Register(db)
	ln, err := net.Listen("tcp", ":"+port)
	if err != nil {
		panic(fmt.Sprintf("[ORIGIN] Failed to listen: %v", err))
	}
	fmt.Printf("[ORIGIN] Database listening on port %s (read delay: %v)\n", port, delay)
	fmt.Printf("[ORIGIN] Pre-loaded %d keys\n", len(db.store))
	server.Accept(ln)
}

// OriginClient is used by cache nodes to talk to the origin
type OriginClient struct {
	addr string
}

func NewOriginClient(addr string) *OriginClient {
	return &OriginClient{addr: addr}
}

func (oc *OriginClient) Get(key string) (string, bool) {
	var reply OriginGetReply
	err := callRPC(oc.addr, "OriginDB.Get", &OriginGetArgs{Key: key}, &reply)
	if err != nil {
		fmt.Printf("[ORIGIN CLIENT] Get failed: %v\n", err)
		return "", false
	}
	return reply.Value, reply.Found
}

func (oc *OriginClient) Set(key, value string) bool {
	var reply OriginSetReply
	err := callRPC(oc.addr, "OriginDB.Set", &OriginSetArgs{Key: key, Value: value}, &reply)
	if err != nil {
		fmt.Printf("[ORIGIN CLIENT] Set failed: %v\n", err)
		return false
	}
	return reply.Success
}
